# Site settings
title: TELECOM DESIGN Internet of Things global enabler
email: contact@telecomdesign.fr
description: > # this means to ignore newlines until "baseurl:"
  Telecom Design provides IoT technologies and solutions for various businesses and markets like security, health, tracking...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

host: 0.0.0.0


gems:
- jekyll-compass
